tabWidth: 4
printWidth: 100
singleQuote: true
plugins:
  - 'prettier-plugin-svelte'
overrides:
  - files: ['*.yml', '*.yaml', '*.json', '*.html']
    options:
      tabWidth: 2
  - files: ['*.svelte']
    options:
      parser: 'svelte'
